
select * from categories
insert categories(title) values(N'Áo thun')
insert categories(title) values(N'Áo sơ mi')
insert categories(title) values(N'Áo nỉ')
insert categories(title) values(N'Áo khoác')

select top 5 * from Products 
order by CreateDate desc

-----------T-shirt-------------
insert Products(Title, Preview, Price, CategoryId) values(N'T-SHIRT WHITE',N'Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn. Như cổ điển, đây là trang phục nói với mọi người đàn ông. Được thiết kế để đứng vững trước sự thử thách của thời gian, chiếc áo phông cổ thuyền cắt thẳng đặc trưng của chúng tôi được làm từ áo bông Ai Cập dày dặn cao cấp và được nhấn nhá bằng đường viền cổ áo có gân. Đóng vai trò vừa đóng vai trò chủ chốt, vừa là món đồ thiết yếu, đây sẽ là món đồ được mặc nhiều nhất trong tủ quần áo của bạn.',200000,1)
insert Products(Title, Preview, Price, CategoryId) values(N'T-SHIRT BLACK',N'Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn. Như cổ điển, đây là trang phục nói với mọi người đàn ông. Được thiết kế để đứng vững trước sự thử thách của thời gian, chiếc áo phông cổ thuyền cắt thẳng đặc trưng của chúng tôi được làm từ áo bông Ai Cập dày dặn cao cấp và được nhấn nhá bằng đường viền cổ áo có gân. Đóng vai trò vừa đóng vai trò chủ chốt, vừa là món đồ thiết yếu, đây sẽ là món đồ được mặc nhiều nhất trong tủ quần áo của bạn.',200000,1)
insert Products(Title, Preview, Price, CategoryId) values(N'T-SHIRT MELANGE',N'Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn. Như cổ điển, đây là trang phục nói với mọi người đàn ông. Được thiết kế để đứng vững trước sự thử thách của thời gian, chiếc áo phông cổ thuyền cắt thẳng đặc trưng của chúng tôi được làm từ áo bông Ai Cập dày dặn cao cấp và được nhấn nhá bằng đường viền cổ áo có gân. Đóng vai trò vừa đóng vai trò chủ chốt, vừa là món đồ thiết yếu, đây sẽ là món đồ được mặc nhiều nhất trong tủ quần áo của bạn.',200000,1)
insert Products(Title, Preview, Price, CategoryId) values(N'T-SHIRT DARK NAVY',N'Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn. Như cổ điển, đây là trang phục nói với mọi người đàn ông. Được thiết kế để đứng vững trước sự thử thách của thời gian, chiếc áo phông cổ thuyền cắt thẳng đặc trưng của chúng tôi được làm từ áo bông Ai Cập dày dặn cao cấp và được nhấn nhá bằng đường viền cổ áo có gân. Đóng vai trò vừa đóng vai trò chủ chốt, vừa là món đồ thiết yếu, đây sẽ là món đồ được mặc nhiều nhất trong tủ quần áo của bạn.',200000,1)
insert Products(Title, Preview, Price, CategoryId) values(N'T-SHIRT CHARCOAL MELANGE',N'Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn. Như cổ điển, đây là trang phục nói với mọi người đàn ông. Được thiết kế để đứng vững trước sự thử thách của thời gian, chiếc áo phông cổ thuyền cắt thẳng đặc trưng của chúng tôi được làm từ áo bông Ai Cập dày dặn cao cấp và được nhấn nhá bằng đường viền cổ áo có gân. Đóng vai trò vừa đóng vai trò chủ chốt, vừa là món đồ thiết yếu, đây sẽ là món đồ được mặc nhiều nhất trong tủ quần áo của bạn.',200000,1)
insert Products(Title, Preview, Price, CategoryId) values(N'T-SHIRT DUSTY GREEN',N'Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn. Như cổ điển, đây là trang phục nói với mọi người đàn ông. Được thiết kế để đứng vững trước sự thử thách của thời gian, chiếc áo phông cổ thuyền cắt thẳng đặc trưng của chúng tôi được làm từ áo bông Ai Cập dày dặn cao cấp và được nhấn nhá bằng đường viền cổ áo có gân. Đóng vai trò vừa đóng vai trò chủ chốt, vừa là món đồ thiết yếu, đây sẽ là món đồ được mặc nhiều nhất trong tủ quần áo của bạn.',200000,1)
insert Products(Title, Preview, Price, CategoryId) values(N'T-SHIRT BURGUNDY',N'Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn. Như cổ điển, đây là trang phục nói với mọi người đàn ông. Được thiết kế để đứng vững trước sự thử thách của thời gian, chiếc áo phông cổ thuyền cắt thẳng đặc trưng của chúng tôi được làm từ áo bông Ai Cập dày dặn cao cấp và được nhấn nhá bằng đường viền cổ áo có gân. Đóng vai trò vừa đóng vai trò chủ chốt, vừa là món đồ thiết yếu, đây sẽ là món đồ được mặc nhiều nhất trong tủ quần áo của bạn.',200000,1)

insert Products(Title, Preview, Price, CategoryId) values(N'The Long Sleeve T-Shirt WHITE',N'Một mặt hàng chủ lực dễ sử dụng quanh năm có trong tủ quần áo của mỗi người đàn ông. Áo phông dài tay của chúng tôi được làm thủ công từ loại bông chải kỹ nặng tùy chỉnh, được thiết kế để giữ cho bạn mát mẻ và được cắt cho vừa vặn để tạo ra một chiếc rèm sắc nét nhưng thoải mái. Cho dù nó được đeo một mình hay đế để xếp lớp, nó sẽ là một bổ sung linh hoạt cho dòng sản phẩm cốt lõi của bạn. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',250000,1)
insert Products(Title, Preview, Price, CategoryId) values(N'The Long Sleeve T-Shirt GRAY MELANGE',N'Một mặt hàng chủ lực dễ sử dụng quanh năm có trong tủ quần áo của mỗi người đàn ông. Áo phông dài tay của chúng tôi được làm thủ công từ loại bông chải kỹ nặng tùy chỉnh, được thiết kế để giữ cho bạn mát mẻ và được cắt cho vừa vặn để tạo ra một chiếc rèm sắc nét nhưng thoải mái. Cho dù nó được đeo một mình hay đế để xếp lớp, nó sẽ là một bổ sung linh hoạt cho dòng sản phẩm cốt lõi của bạn. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',250000,1)
insert Products(Title, Preview, Price, CategoryId) values(N'The Long Sleeve T-Shirt DARK NAVY',N'Một mặt hàng chủ lực dễ sử dụng quanh năm có trong tủ quần áo của mỗi người đàn ông. Áo phông dài tay của chúng tôi được làm thủ công từ loại bông chải kỹ nặng tùy chỉnh, được thiết kế để giữ cho bạn mát mẻ và được cắt cho vừa vặn để tạo ra một chiếc rèm sắc nét nhưng thoải mái. Cho dù nó được đeo một mình hay đế để xếp lớp, nó sẽ là một bổ sung linh hoạt cho dòng sản phẩm cốt lõi của bạn. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',250000,1)
insert Products(Title, Preview, Price, CategoryId) values(N'The Long Sleeve T-Shirt BLACK',N'Một mặt hàng chủ lực dễ sử dụng quanh năm có trong tủ quần áo của mỗi người đàn ông. Áo phông dài tay của chúng tôi được làm thủ công từ loại bông chải kỹ nặng tùy chỉnh, được thiết kế để giữ cho bạn mát mẻ và được cắt cho vừa vặn để tạo ra một chiếc rèm sắc nét nhưng thoải mái. Cho dù nó được đeo một mình hay đế để xếp lớp, nó sẽ là một bổ sung linh hoạt cho dòng sản phẩm cốt lõi của bạn. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',250000,1)
insert Products(Title, Preview, Price, CategoryId) values(N'The Long Sleeve T-Shirt OFF WHITE',N'Một mặt hàng chủ lực dễ sử dụng quanh năm có trong tủ quần áo của mỗi người đàn ông. Áo phông dài tay của chúng tôi được làm thủ công từ loại bông chải kỹ nặng tùy chỉnh, được thiết kế để giữ cho bạn mát mẻ và được cắt cho vừa vặn để tạo ra một chiếc rèm sắc nét nhưng thoải mái. Cho dù nó được đeo một mình hay đế để xếp lớp, nó sẽ là một bổ sung linh hoạt cho dòng sản phẩm cốt lõi của bạn. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',250000,1)

insert Products(Title, Preview, Price, CategoryId) values(N'The Pique Polo WHITE',N'Ra mắt trên sân quần vợt vào những năm 1920, chiếc áo Pique Polo lấp đầy khoảng trống giữa áo sơ mi và áo phông. Được giới thiệu lần đầu tiên trong bộ sưu tập vĩnh viễn của chúng tôi vào năm 2016, đây là bản cập nhật phiên bản thứ năm của chúng tôi: Cốt lõi của nó là một loại vải dệt kim hữu cơ mềm mại và đáng kể, thoáng khí được phát triển tùy chỉnh. Hình bóng cắt thẳng của chúng tôi được tô điểm bằng một cổ áo cân đối hoàn hảo và một chiếc áo khoác dạ kiểu Pháp liền mạch với những chiếc cúc xà cừ có tông màu đặc trưng của chúng tôi. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',220000,1)
insert Products(Title, Preview, Price, CategoryId) values(N'The Pique Polo DARK NAVY',N'Ra mắt trên sân quần vợt vào những năm 1920, chiếc áo Pique Polo lấp đầy khoảng trống giữa áo sơ mi và áo phông. Được giới thiệu lần đầu tiên trong bộ sưu tập vĩnh viễn của chúng tôi vào năm 2016, đây là bản cập nhật phiên bản thứ năm của chúng tôi: Cốt lõi của nó là một loại vải dệt kim hữu cơ mềm mại và đáng kể, thoáng khí được phát triển tùy chỉnh. Hình bóng cắt thẳng của chúng tôi được tô điểm bằng một cổ áo cân đối hoàn hảo và một chiếc áo khoác dạ kiểu Pháp liền mạch với những chiếc cúc xà cừ có tông màu đặc trưng của chúng tôi. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',220000,1)
insert Products(Title, Preview, Price, CategoryId) values(N'The Pique Polo BLACK',N'Ra mắt trên sân quần vợt vào những năm 1920, chiếc áo Pique Polo lấp đầy khoảng trống giữa áo sơ mi và áo phông. Được giới thiệu lần đầu tiên trong bộ sưu tập vĩnh viễn của chúng tôi vào năm 2016, đây là bản cập nhật phiên bản thứ năm của chúng tôi: Cốt lõi của nó là một loại vải dệt kim hữu cơ mềm mại và đáng kể, thoáng khí được phát triển tùy chỉnh. Hình bóng cắt thẳng của chúng tôi được tô điểm bằng một cổ áo cân đối hoàn hảo và một chiếc áo khoác dạ kiểu Pháp liền mạch với những chiếc cúc xà cừ có tông màu đặc trưng của chúng tôi. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',220000,1)
insert Products(Title, Preview, Price, CategoryId) values(N'The Pique Polo DARK OLIVE',N'Ra mắt trên sân quần vợt vào những năm 1920, chiếc áo Pique Polo lấp đầy khoảng trống giữa áo sơ mi và áo phông. Được giới thiệu lần đầu tiên trong bộ sưu tập vĩnh viễn của chúng tôi vào năm 2016, đây là bản cập nhật phiên bản thứ năm của chúng tôi: Cốt lõi của nó là một loại vải dệt kim hữu cơ mềm mại và đáng kể, thoáng khí được phát triển tùy chỉnh. Hình bóng cắt thẳng của chúng tôi được tô điểm bằng một cổ áo cân đối hoàn hảo và một chiếc áo khoác dạ kiểu Pháp liền mạch với những chiếc cúc xà cừ có tông màu đặc trưng của chúng tôi. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',220000,1)


---- SHIRT -------

insert Products(Title, Preview, Price, CategoryId) values(N'The Oxford Shirt WHITE',N'Là món đồ cổ điển không thể thiếu trong mọi tủ quần áo, chiếc áo sơ mi cài nút bằng vải Oxford là thiết yếu vượt thời gian. Áo sơ mi của chúng tôi có kiểu dáng cắt thẳng, vải Oxford 100% cotton hữu cơ được chải mềm và các nút Mother of Pearl tùy chỉnh. Cho dù bạn kết hợp nó với denim hay quần tây, không có tủ quần áo nào là hoàn chỉnh nếu thiếu một chiếc. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',280000,2)
insert Products(Title, Preview, Price, CategoryId) values(N'The Oxford Shirt LIGHT GREY',N'Là món đồ cổ điển không thể thiếu trong mọi tủ quần áo, chiếc áo sơ mi cài nút bằng vải Oxford là thiết yếu vượt thời gian. Áo sơ mi của chúng tôi có kiểu dáng cắt thẳng, vải Oxford 100% cotton hữu cơ được chải mềm và các nút Mother of Pearl tùy chỉnh. Cho dù bạn kết hợp nó với denim hay quần tây, không có tủ quần áo nào là hoàn chỉnh nếu thiếu một chiếc. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',280000,2)
insert Products(Title, Preview, Price, CategoryId) values(N'The Oxford Shirt BLUE',N'Là món đồ cổ điển không thể thiếu trong mọi tủ quần áo, chiếc áo sơ mi cài nút bằng vải Oxford là thiết yếu vượt thời gian. Áo sơ mi của chúng tôi có kiểu dáng cắt thẳng, vải Oxford 100% cotton hữu cơ được chải mềm và các nút Mother of Pearl tùy chỉnh. Cho dù bạn kết hợp nó với denim hay quần tây, không có tủ quần áo nào là hoàn chỉnh nếu thiếu một chiếc. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',280000,2)
insert Products(Title, Preview, Price, CategoryId) values(N'The Oxford Shirt DARK NAVY',N'Là món đồ cổ điển không thể thiếu trong mọi tủ quần áo, chiếc áo sơ mi cài nút bằng vải Oxford là thiết yếu vượt thời gian. Áo sơ mi của chúng tôi có kiểu dáng cắt thẳng, vải Oxford 100% cotton hữu cơ được chải mềm và các nút Mother of Pearl tùy chỉnh. Cho dù bạn kết hợp nó với denim hay quần tây, không có tủ quần áo nào là hoàn chỉnh nếu thiếu một chiếc. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',280000,2)
insert Products(Title, Preview, Price, CategoryId) values(N'The Oxford Shirt DARK GREEN',N'Là món đồ cổ điển không thể thiếu trong mọi tủ quần áo, chiếc áo sơ mi cài nút bằng vải Oxford là thiết yếu vượt thời gian. Áo sơ mi của chúng tôi có kiểu dáng cắt thẳng, vải Oxford 100% cotton hữu cơ được chải mềm và các nút Mother of Pearl tùy chỉnh. Cho dù bạn kết hợp nó với denim hay quần tây, không có tủ quần áo nào là hoàn chỉnh nếu thiếu một chiếc. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',280000,2)
insert Products(Title, Preview, Price, CategoryId) values(N'The Oxford Shirt BLUE STRIPE',N'Là món đồ cổ điển không thể thiếu trong mọi tủ quần áo, chiếc áo sơ mi cài nút bằng vải Oxford là thiết yếu vượt thời gian. Áo sơ mi của chúng tôi có kiểu dáng cắt thẳng, vải Oxford 100% cotton hữu cơ được chải mềm và các nút Mother of Pearl tùy chỉnh. Cho dù bạn kết hợp nó với denim hay quần tây, không có tủ quần áo nào là hoàn chỉnh nếu thiếu một chiếc. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',280000,2)
insert Products(Title, Preview, Price, CategoryId) values(N'The Oxford Shirt LIGHT GREY STRIPE',N'Là món đồ cổ điển không thể thiếu trong mọi tủ quần áo, chiếc áo sơ mi cài nút bằng vải Oxford là thiết yếu vượt thời gian. Áo sơ mi của chúng tôi có kiểu dáng cắt thẳng, vải Oxford 100% cotton hữu cơ được chải mềm và các nút Mother of Pearl tùy chỉnh. Cho dù bạn kết hợp nó với denim hay quần tây, không có tủ quần áo nào là hoàn chỉnh nếu thiếu một chiếc. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',280000,2)

insert Products(Title, Preview, Price, CategoryId) values(N'The Denim Shirt STONE BLEACH',N'Áo sơ mi denim đã phát triển từ nguồn gốc trang phục bảo hộ lao động truyền thống của nó thành một kiểu dáng cổ điển mới. Loại bỏ các chi tiết không cần thiết, chiếc áo của chúng tôi được cắt từ một cấu trúc dệt nhuộm chàm dày đặc, có tay cầm mềm mại sẽ chỉ tốt hơn theo thời gian. Cho dù bạn mặc nó một mình, nhiều lớp hay mặc như một chiếc áo sơ mi - đó là một sự lựa chọn đáng tin cậy. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',365000,2)
insert Products(Title, Preview, Price, CategoryId) values(N'The Denim Shirt STONE WASH',N'Áo sơ mi denim đã phát triển từ nguồn gốc trang phục bảo hộ lao động truyền thống của nó thành một kiểu dáng cổ điển mới. Loại bỏ các chi tiết không cần thiết, chiếc áo của chúng tôi được cắt từ một cấu trúc dệt nhuộm chàm dày đặc, có tay cầm mềm mại sẽ chỉ tốt hơn theo thời gian. Cho dù bạn mặc nó một mình, nhiều lớp hay mặc như một chiếc áo sơ mi - đó là một sự lựa chọn đáng tin cậy. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',365000,2)

insert Products(Title, Preview, Price, CategoryId) values(N'The Linen Shirt WHITE',N'Một sự lựa chọn tự nhiên cho những ngày hè và nơi nghỉ ngơi ấm áp. Được cắt từ vải lanh 100% chỉ mềm hơn khi giặt và mặc, được thiết kế riêng để vừa vặn thoải mái và có các nút khảm xà cừ. Một sự lựa chọn nhẹ nhàng hơn, sẽ phù hợp với các bữa tiệc nướng cuối tuần cũng như trong mùa cưới. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',360000,2)
insert Products(Title, Preview, Price, CategoryId) values(N'The Linen Shirt BEIGE',N'Một sự lựa chọn tự nhiên cho những ngày hè và nơi nghỉ ngơi ấm áp. Được cắt từ vải lanh 100% chỉ mềm hơn khi giặt và mặc, được thiết kế riêng để vừa vặn thoải mái và có các nút khảm xà cừ. Một sự lựa chọn nhẹ nhàng hơn, sẽ phù hợp với các bữa tiệc nướng cuối tuần cũng như trong mùa cưới. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',360000,2)
insert Products(Title, Preview, Price, CategoryId) values(N'The Linen Shirt DARK NAVY',N'Một sự lựa chọn tự nhiên cho những ngày hè và nơi nghỉ ngơi ấm áp. Được cắt từ vải lanh 100% chỉ mềm hơn khi giặt và mặc, được thiết kế riêng để vừa vặn thoải mái và có các nút khảm xà cừ. Một sự lựa chọn nhẹ nhàng hơn, sẽ phù hợp với các bữa tiệc nướng cuối tuần cũng như trong mùa cưới. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',360000,2)
insert Products(Title, Preview, Price, CategoryId) values(N'The Linen Shirt OLIVE',N'Một sự lựa chọn tự nhiên cho những ngày hè và nơi nghỉ ngơi ấm áp. Được cắt từ vải lanh 100% chỉ mềm hơn khi giặt và mặc, được thiết kế riêng để vừa vặn thoải mái và có các nút khảm xà cừ. Một sự lựa chọn nhẹ nhàng hơn, sẽ phù hợp với các bữa tiệc nướng cuối tuần cũng như trong mùa cưới. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',360000,2)
insert Products(Title, Preview, Price, CategoryId) values(N'The Linen Shirt BLUE STRIPE',N'Một sự lựa chọn tự nhiên cho những ngày hè và nơi nghỉ ngơi ấm áp. Được cắt từ vải lanh 100% chỉ mềm hơn khi giặt và mặc, được thiết kế riêng để vừa vặn thoải mái và có các nút khảm xà cừ. Một sự lựa chọn nhẹ nhàng hơn, sẽ phù hợp với các bữa tiệc nướng cuối tuần cũng như trong mùa cưới. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',360000,2)
insert Products(Title, Preview, Price, CategoryId) values(N'The Linen Shirt LIGHT BLUE',N'Một sự lựa chọn tự nhiên cho những ngày hè và nơi nghỉ ngơi ấm áp. Được cắt từ vải lanh 100% chỉ mềm hơn khi giặt và mặc, được thiết kế riêng để vừa vặn thoải mái và có các nút khảm xà cừ. Một sự lựa chọn nhẹ nhàng hơn, sẽ phù hợp với các bữa tiệc nướng cuối tuần cũng như trong mùa cưới. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',360000,2)

insert Products(Title, Preview, Price, CategoryId) values(N'The Overshirt DARK NAVY',N'Một cổ điển bảo hộ lao động tái sinh. Lấy cảm hứng từ bộ đồng phục công nhân nguyên bản “Bleu de Travail” của Pháp, The Overshirt có đường cắt thẳng, 3 túi trước cổ điển và được thiết kế từ 100% sợi cotton hữu cơ. Dù bạn là MacGyver hay chưa bao giờ sử dụng một công cụ điện nào trong đời, sự kết hợp giữa vải cấp độ quân sự và đường may cẩn thận của The Overshirt sẽ hoàn thiện vẻ ngoài của bạn. Đây là lớp trên cùng hoàn hảo cho những ngày ấm áp và là lớp giữa khi nhiệt độ giảm xuống. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',420000,2)
insert Products(Title, Preview, Price, CategoryId) values(N'The Overshirt OLIVE',N'Một cổ điển bảo hộ lao động tái sinh. Lấy cảm hứng từ bộ đồng phục công nhân nguyên bản “Bleu de Travail” của Pháp, The Overshirt có đường cắt thẳng, 3 túi trước cổ điển và được thiết kế từ 100% sợi cotton hữu cơ. Dù bạn là MacGyver hay chưa bao giờ sử dụng một công cụ điện nào trong đời, sự kết hợp giữa vải cấp độ quân sự và đường may cẩn thận của The Overshirt sẽ hoàn thiện vẻ ngoài của bạn. Đây là lớp trên cùng hoàn hảo cho những ngày ấm áp và là lớp giữa khi nhiệt độ giảm xuống. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',420000,2)
insert Products(Title, Preview, Price, CategoryId) values(N'The Overshirt BEIGE',N'Một cổ điển bảo hộ lao động tái sinh. Lấy cảm hứng từ bộ đồng phục công nhân nguyên bản “Bleu de Travail” của Pháp, The Overshirt có đường cắt thẳng, 3 túi trước cổ điển và được thiết kế từ 100% sợi cotton hữu cơ. Dù bạn là MacGyver hay chưa bao giờ sử dụng một công cụ điện nào trong đời, sự kết hợp giữa vải cấp độ quân sự và đường may cẩn thận của The Overshirt sẽ hoàn thiện vẻ ngoài của bạn. Đây là lớp trên cùng hoàn hảo cho những ngày ấm áp và là lớp giữa khi nhiệt độ giảm xuống. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',420000,2)
insert Products(Title, Preview, Price, CategoryId) values(N'The Overshirt TAUPE',N'Một cổ điển bảo hộ lao động tái sinh. Lấy cảm hứng từ bộ đồng phục công nhân nguyên bản “Bleu de Travail” của Pháp, The Overshirt có đường cắt thẳng, 3 túi trước cổ điển và được thiết kế từ 100% sợi cotton hữu cơ. Dù bạn là MacGyver hay chưa bao giờ sử dụng một công cụ điện nào trong đời, sự kết hợp giữa vải cấp độ quân sự và đường may cẩn thận của The Overshirt sẽ hoàn thiện vẻ ngoài của bạn. Đây là lớp trên cùng hoàn hảo cho những ngày ấm áp và là lớp giữa khi nhiệt độ giảm xuống. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',420000,2)
insert Products(Title, Preview, Price, CategoryId) values(N'The Overshirt KHAKI GREEN',N'Một cổ điển bảo hộ lao động tái sinh. Lấy cảm hứng từ bộ đồng phục công nhân nguyên bản “Bleu de Travail” của Pháp, The Overshirt có đường cắt thẳng, 3 túi trước cổ điển và được thiết kế từ 100% sợi cotton hữu cơ. Dù bạn là MacGyver hay chưa bao giờ sử dụng một công cụ điện nào trong đời, sự kết hợp giữa vải cấp độ quân sự và đường may cẩn thận của The Overshirt sẽ hoàn thiện vẻ ngoài của bạn. Đây là lớp trên cùng hoàn hảo cho những ngày ấm áp và là lớp giữa khi nhiệt độ giảm xuống. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',420000,2)
insert Products(Title, Preview, Price, CategoryId) values(N'The Overshirt BLACK',N'Một cổ điển bảo hộ lao động tái sinh. Lấy cảm hứng từ bộ đồng phục công nhân nguyên bản “Bleu de Travail” của Pháp, The Overshirt có đường cắt thẳng, 3 túi trước cổ điển và được thiết kế từ 100% sợi cotton hữu cơ. Dù bạn là MacGyver hay chưa bao giờ sử dụng một công cụ điện nào trong đời, sự kết hợp giữa vải cấp độ quân sự và đường may cẩn thận của The Overshirt sẽ hoàn thiện vẻ ngoài của bạn. Đây là lớp trên cùng hoàn hảo cho những ngày ấm áp và là lớp giữa khi nhiệt độ giảm xuống. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',420000,2)


insert Products(Title, Preview, Price, CategoryId) values(N'The Wool Overshirt KHAKI GREEN',N'Một kiểu trang phục cổ điển khác được tái sinh, The Wool Overshirt được lấy cảm hứng từ bộ đồng phục ban đầu của công nhân Pháp "Bleu de Travail". Được may từ sợi len đan chéo có trọng lượng trung bình, được làm từ 100% len tái chế, nó sẽ giúp bạn giữ ấm và khô ráo trong phong cách và là lớp trên cùng lý tưởng cho thời tiết chuyển mùa. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',420000,2)
insert Products(Title, Preview, Price, CategoryId) values(N'The Wool Overshirt CHARCOAL MELANGE',N'Một kiểu trang phục cổ điển khác được tái sinh, The Wool Overshirt được lấy cảm hứng từ bộ đồng phục ban đầu của công nhân Pháp "Bleu de Travail". Được may từ sợi len đan chéo có trọng lượng trung bình, được làm từ 100% len tái chế, nó sẽ giúp bạn giữ ấm và khô ráo trong phong cách và là lớp trên cùng lý tưởng cho thời tiết chuyển mùa. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',420000,2)
insert Products(Title, Preview, Price, CategoryId) values(N'The Wool Overshirt DARK NAVY',N'Một kiểu trang phục cổ điển khác được tái sinh, The Wool Overshirt được lấy cảm hứng từ bộ đồng phục ban đầu của công nhân Pháp "Bleu de Travail". Được may từ sợi len đan chéo có trọng lượng trung bình, được làm từ 100% len tái chế, nó sẽ giúp bạn giữ ấm và khô ráo trong phong cách và là lớp trên cùng lý tưởng cho thời tiết chuyển mùa. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',420000,2)

insert Products(Title, Preview, Price, CategoryId) values(N'TThe Flannel Shirt CHARCOAL MELANGE',N'Chúng tôi mang phong cách cổ điển về trang phục bảo hộ lao động của Mỹ vượt qua cả văn hóa hipster thập niên 90 và thập niên 00 với đường cắt không rườm rà, cổ áo cài nút cổ điển và cấu trúc đan chéo tinh tế được thiết kế cho hàng ngày. Được cắt từ vải chéo mềm, chải kỹ, được phát triển tùy chỉnh của Ý được làm từ 100% bông hữu cơ, Áo sơ mi Flannel là một sự thay thế chắc chắn cho áo sơ mi trang trọng bằng cách kết hợp sự thoải mái và phong cách không giống như những chiếc áo sơ mi khác trong dòng sản phẩm của chúng tôi. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',420000,2)
insert Products(Title, Preview, Price, CategoryId) values(N'TThe Flannel Shirt DARK NAVY',N'Chúng tôi mang phong cách cổ điển về trang phục bảo hộ lao động của Mỹ vượt qua cả văn hóa hipster thập niên 90 và thập niên 00 với đường cắt không rườm rà, cổ áo cài nút cổ điển và cấu trúc đan chéo tinh tế được thiết kế cho hàng ngày. Được cắt từ vải chéo mềm, chải kỹ, được phát triển tùy chỉnh của Ý được làm từ 100% bông hữu cơ, Áo sơ mi Flannel là một sự thay thế chắc chắn cho áo sơ mi trang trọng bằng cách kết hợp sự thoải mái và phong cách không giống như những chiếc áo sơ mi khác trong dòng sản phẩm của chúng tôi. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',420000,2)
insert Products(Title, Preview, Price, CategoryId) values(N'TThe Flannel Shirt KHAKI GREEN',N'Chúng tôi mang phong cách cổ điển về trang phục bảo hộ lao động của Mỹ vượt qua cả văn hóa hipster thập niên 90 và thập niên 00 với đường cắt không rườm rà, cổ áo cài nút cổ điển và cấu trúc đan chéo tinh tế được thiết kế cho hàng ngày. Được cắt từ vải chéo mềm, chải kỹ, được phát triển tùy chỉnh của Ý được làm từ 100% bông hữu cơ, Áo sơ mi Flannel là một sự thay thế chắc chắn cho áo sơ mi trang trọng bằng cách kết hợp sự thoải mái và phong cách không giống như những chiếc áo sơ mi khác trong dòng sản phẩm của chúng tôi. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',420000,2)
insert Products(Title, Preview, Price, CategoryId) values(N'TThe Flannel Shirt GREY MELANGE MELANGE',N'Chúng tôi mang phong cách cổ điển về trang phục bảo hộ lao động của Mỹ vượt qua cả văn hóa hipster thập niên 90 và thập niên 00 với đường cắt không rườm rà, cổ áo cài nút cổ điển và cấu trúc đan chéo tinh tế được thiết kế cho hàng ngày. Được cắt từ vải chéo mềm, chải kỹ, được phát triển tùy chỉnh của Ý được làm từ 100% bông hữu cơ, Áo sơ mi Flannel là một sự thay thế chắc chắn cho áo sơ mi trang trọng bằng cách kết hợp sự thoải mái và phong cách không giống như những chiếc áo sơ mi khác trong dòng sản phẩm của chúng tôi. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',420000,2)



--The Sweatshirt---

insert Products(Title, Preview, Price, CategoryId) values(N'The Sweatshirt GREY MELANGE',N'Chúng tôi đã làm lại một tác phẩm cổ điển với sự tối giản của chúng tôi về bộ đồng phục cầu thủ bóng đá Mỹ nguyên bản. Được cắt từ loại bông Ai Cập không chải được phát triển tùy chỉnh của chúng tôi, có thiết kế vừa vặn nhưng cực kỳ thoải mái và nội thất mềm mại của chúng tôi. Hoàn hảo cho những ngày Chủ nhật chậm rãi ở nhà, nhưng vẫn đủ sắc nét để dạo phố. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',230000,3)
insert Products(Title, Preview, Price, CategoryId) values(N'The Sweatshirt DARK NAVY',N'Chúng tôi đã làm lại một tác phẩm cổ điển với sự tối giản của chúng tôi về bộ đồng phục cầu thủ bóng đá Mỹ nguyên bản. Được cắt từ loại bông Ai Cập không chải được phát triển tùy chỉnh của chúng tôi, có thiết kế vừa vặn nhưng cực kỳ thoải mái và nội thất mềm mại của chúng tôi. Hoàn hảo cho những ngày Chủ nhật chậm rãi ở nhà, nhưng vẫn đủ sắc nét để dạo phố. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',230000,3)
insert Products(Title, Preview, Price, CategoryId) values(N'The Sweatshirt BLACK',N'Chúng tôi đã làm lại một tác phẩm cổ điển với sự tối giản của chúng tôi về bộ đồng phục cầu thủ bóng đá Mỹ nguyên bản. Được cắt từ loại bông Ai Cập không chải được phát triển tùy chỉnh của chúng tôi, có thiết kế vừa vặn nhưng cực kỳ thoải mái và nội thất mềm mại của chúng tôi. Hoàn hảo cho những ngày Chủ nhật chậm rãi ở nhà, nhưng vẫn đủ sắc nét để dạo phố. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',230000,3)
insert Products(Title, Preview, Price, CategoryId) values(N'The Sweatshirt DUSTY GREEN',N'Chúng tôi đã làm lại một tác phẩm cổ điển với sự tối giản của chúng tôi về bộ đồng phục cầu thủ bóng đá Mỹ nguyên bản. Được cắt từ loại bông Ai Cập không chải được phát triển tùy chỉnh của chúng tôi, có thiết kế vừa vặn nhưng cực kỳ thoải mái và nội thất mềm mại của chúng tôi. Hoàn hảo cho những ngày Chủ nhật chậm rãi ở nhà, nhưng vẫn đủ sắc nét để dạo phố. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',230000,3)
insert Products(Title, Preview, Price, CategoryId) values(N'The Sweatshirt BURGUNDY',N'Chúng tôi đã làm lại một tác phẩm cổ điển với sự tối giản của chúng tôi về bộ đồng phục cầu thủ bóng đá Mỹ nguyên bản. Được cắt từ loại bông Ai Cập không chải được phát triển tùy chỉnh của chúng tôi, có thiết kế vừa vặn nhưng cực kỳ thoải mái và nội thất mềm mại của chúng tôi. Hoàn hảo cho những ngày Chủ nhật chậm rãi ở nhà, nhưng vẫn đủ sắc nét để dạo phố. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',230000,3)
insert Products(Title, Preview, Price, CategoryId) values(N'The Sweatshirt OFF WHITE',N'Chúng tôi đã làm lại một tác phẩm cổ điển với sự tối giản của chúng tôi về bộ đồng phục cầu thủ bóng đá Mỹ nguyên bản. Được cắt từ loại bông Ai Cập không chải được phát triển tùy chỉnh của chúng tôi, có thiết kế vừa vặn nhưng cực kỳ thoải mái và nội thất mềm mại của chúng tôi. Hoàn hảo cho những ngày Chủ nhật chậm rãi ở nhà, nhưng vẫn đủ sắc nét để dạo phố. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',230000,3)

insert Products(Title, Preview, Price, CategoryId) values(N'The Hoodie GREY MELANGE',N'Với nguồn gốc từ điền kinh và phản văn hóa, áo hoodie đã phát triển thành một mặt hàng thiết yếu. Được cắt từ sợi dây quấn vải cotton 100% hữu cơ được phát triển tùy chỉnh của chúng tôi, The Hoodie có mũ trùm đầu hai lớp có kích thước rộng rãi, nhưng được loại bỏ khỏi các chi tiết thông thường, không cần thiết. Bằng cách tối ưu hóa cho hình thức và chức năng thực tế (loại bỏ những thứ tương tự như túi đựng đồ), chúng tôi đã tạo ra một phần nâng cao đánh vần sự tinh tế, thay vì mặc thiếu, làm cho nó trở thành một lớp đi kèm cả khi bật - và tắt - đồng hồ. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',280000,3)
insert Products(Title, Preview, Price, CategoryId) values(N'The Hoodie DARK NAVY',N'Với nguồn gốc từ điền kinh và phản văn hóa, áo hoodie đã phát triển thành một mặt hàng thiết yếu. Được cắt từ sợi dây quấn vải cotton 100% hữu cơ được phát triển tùy chỉnh của chúng tôi, The Hoodie có mũ trùm đầu hai lớp có kích thước rộng rãi, nhưng được loại bỏ khỏi các chi tiết thông thường, không cần thiết. Bằng cách tối ưu hóa cho hình thức và chức năng thực tế (loại bỏ những thứ tương tự như túi đựng đồ), chúng tôi đã tạo ra một phần nâng cao đánh vần sự tinh tế, thay vì mặc thiếu, làm cho nó trở thành một lớp đi kèm cả khi bật - và tắt - đồng hồ. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',280000,3)
insert Products(Title, Preview, Price, CategoryId) values(N'The Hoodie BLACK',N'Với nguồn gốc từ điền kinh và phản văn hóa, áo hoodie đã phát triển thành một mặt hàng thiết yếu. Được cắt từ sợi dây quấn vải cotton 100% hữu cơ được phát triển tùy chỉnh của chúng tôi, The Hoodie có mũ trùm đầu hai lớp có kích thước rộng rãi, nhưng được loại bỏ khỏi các chi tiết thông thường, không cần thiết. Bằng cách tối ưu hóa cho hình thức và chức năng thực tế (loại bỏ những thứ tương tự như túi đựng đồ), chúng tôi đã tạo ra một phần nâng cao đánh vần sự tinh tế, thay vì mặc thiếu, làm cho nó trở thành một lớp đi kèm cả khi bật - và tắt - đồng hồ. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',280000,3)
insert Products(Title, Preview, Price, CategoryId) values(N'The Hoodie MUD GREEN',N'Với nguồn gốc từ điền kinh và phản văn hóa, áo hoodie đã phát triển thành một mặt hàng thiết yếu. Được cắt từ sợi dây quấn vải cotton 100% hữu cơ được phát triển tùy chỉnh của chúng tôi, The Hoodie có mũ trùm đầu hai lớp có kích thước rộng rãi, nhưng được loại bỏ khỏi các chi tiết thông thường, không cần thiết. Bằng cách tối ưu hóa cho hình thức và chức năng thực tế (loại bỏ những thứ tương tự như túi đựng đồ), chúng tôi đã tạo ra một phần nâng cao đánh vần sự tinh tế, thay vì mặc thiếu, làm cho nó trở thành một lớp đi kèm cả khi bật - và tắt - đồng hồ. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',280000,3)

insert Products(Title, Preview, Price, CategoryId) values(N'The Zip Hoodie MUD GREEN',N'Vượt qua khuôn mẫu trẻ trung, The Zip Hoodie đã phát triển thành một chiếc áo lớp giản dị với chức năng. Được cắt từ sợi dây quấn ngược được phát triển tùy chỉnh, có trọng lượng nặng, không có lông tơ từ 100% cotton hữu cơ, nó có mũ trùm đầu hai lớp có kích thước rộng rãi, túi bên ẩn và khóa kéo hai chiều. Là hai bộ phận bằng nhau giữa áo len và áo khoác, nó kết hợp tính thiết thực, thoải mái và phong cách không giống ai. Mặc nó với quần chinos và brogues yêu thích của bạn - hoặc chơi nó thật ngầu với denim và giày thể thao trắng. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',330000,3)
insert Products(Title, Preview, Price, CategoryId) values(N'The Zip Hoodie GREY MELANGE',N'Vượt qua khuôn mẫu trẻ trung, The Zip Hoodie đã phát triển thành một chiếc áo lớp giản dị với chức năng. Được cắt từ sợi dây quấn ngược được phát triển tùy chỉnh, có trọng lượng nặng, không có lông tơ từ 100% cotton hữu cơ, nó có mũ trùm đầu hai lớp có kích thước rộng rãi, túi bên ẩn và khóa kéo hai chiều. Là hai bộ phận bằng nhau giữa áo len và áo khoác, nó kết hợp tính thiết thực, thoải mái và phong cách không giống ai. Mặc nó với quần chinos và brogues yêu thích của bạn - hoặc chơi nó thật ngầu với denim và giày thể thao trắng. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',330000,3)
insert Products(Title, Preview, Price, CategoryId) values(N'The Zip Hoodie DARK NAVY',N'Vượt qua khuôn mẫu trẻ trung, The Zip Hoodie đã phát triển thành một chiếc áo lớp giản dị với chức năng. Được cắt từ sợi dây quấn ngược được phát triển tùy chỉnh, có trọng lượng nặng, không có lông tơ từ 100% cotton hữu cơ, nó có mũ trùm đầu hai lớp có kích thước rộng rãi, túi bên ẩn và khóa kéo hai chiều. Là hai bộ phận bằng nhau giữa áo len và áo khoác, nó kết hợp tính thiết thực, thoải mái và phong cách không giống ai. Mặc nó với quần chinos và brogues yêu thích của bạn - hoặc chơi nó thật ngầu với denim và giày thể thao trắng. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',330000,3)
insert Products(Title, Preview, Price, CategoryId) values(N'The Zip Hoodie BLACK',N'Vượt qua khuôn mẫu trẻ trung, The Zip Hoodie đã phát triển thành một chiếc áo lớp giản dị với chức năng. Được cắt từ sợi dây quấn ngược được phát triển tùy chỉnh, có trọng lượng nặng, không có lông tơ từ 100% cotton hữu cơ, nó có mũ trùm đầu hai lớp có kích thước rộng rãi, túi bên ẩn và khóa kéo hai chiều. Là hai bộ phận bằng nhau giữa áo len và áo khoác, nó kết hợp tính thiết thực, thoải mái và phong cách không giống ai. Mặc nó với quần chinos và brogues yêu thích của bạn - hoặc chơi nó thật ngầu với denim và giày thể thao trắng. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',330000,3)


----OuterWear------

insert Products(Title, Preview, Price, CategoryId) values(N'The Car Coat DARK NAVY',N'Một chiếc áo khoác cho tất cả các mùa. Áo khoác Xe hơi được cắt từ một loại vải dệt chéo sợi bông hữu cơ chắc chắn, được xử lý bề mặt không thấm nước và các đường nối dán băng keo để giữ cho bạn khô ráo quanh năm. Từ vải vỏ cho đến lớp lót, đường khâu và thậm chí cả phần gài và khóa kéo, mọi thành phần đều được phát triển để tối đa hóa tuổi thọ của nó trong khi giảm thiểu tác động đến hành tinh của chúng ta. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',690000,4)
insert Products(Title, Preview, Price, CategoryId) values(N'The Car Coat BEIGE',N'Một chiếc áo khoác cho tất cả các mùa. Áo khoác Xe hơi được cắt từ một loại vải dệt chéo sợi bông hữu cơ chắc chắn, được xử lý bề mặt không thấm nước và các đường nối dán băng keo để giữ cho bạn khô ráo quanh năm. Từ vải vỏ cho đến lớp lót, đường khâu và thậm chí cả phần gài và khóa kéo, mọi thành phần đều được phát triển để tối đa hóa tuổi thọ của nó trong khi giảm thiểu tác động đến hành tinh của chúng ta. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',690000,4)

insert Products(Title, Preview, Price, CategoryId) values(N'The Wool Overshirt KHAKI GREEN',N'Một kiểu trang phục cổ điển khác được tái sinh, The Wool Overshirt được lấy cảm hứng từ bộ đồng phục ban đầu của công nhân Pháp "Bleu de Travail". Được may từ sợi len đan chéo có trọng lượng trung bình, được làm từ 100% len tái chế, nó sẽ giúp bạn giữ ấm và khô ráo trong phong cách và là lớp trên cùng lý tưởng cho thời tiết chuyển mùa. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',450000,4)
insert Products(Title, Preview, Price, CategoryId) values(N'The Wool Overshirt CHARCOAL MELANGE',N'Một kiểu trang phục cổ điển khác được tái sinh, The Wool Overshirt được lấy cảm hứng từ bộ đồng phục ban đầu của công nhân Pháp "Bleu de Travail". Được may từ sợi len đan chéo có trọng lượng trung bình, được làm từ 100% len tái chế, nó sẽ giúp bạn giữ ấm và khô ráo trong phong cách và là lớp trên cùng lý tưởng cho thời tiết chuyển mùa. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',450000,4)
insert Products(Title, Preview, Price, CategoryId) values(N'The Wool Overshirt DARK NAVY',N'Một kiểu trang phục cổ điển khác được tái sinh, The Wool Overshirt được lấy cảm hứng từ bộ đồng phục ban đầu của công nhân Pháp "Bleu de Travail". Được may từ sợi len đan chéo có trọng lượng trung bình, được làm từ 100% len tái chế, nó sẽ giúp bạn giữ ấm và khô ráo trong phong cách và là lớp trên cùng lý tưởng cho thời tiết chuyển mùa. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',450000,4)

insert Products(Title, Preview, Price, CategoryId) values(N'The Overshirt DARK NAVY',N'Một cổ điển bảo hộ lao động tái sinh. Lấy cảm hứng từ bộ đồng phục công nhân nguyên bản “Bleu de Travail” của Pháp, The Overshirt có đường cắt thẳng, 3 túi trước cổ điển và được thiết kế từ 100% sợi cotton hữu cơ. Dù bạn là MacGyver hay chưa bao giờ sử dụng một công cụ điện nào trong đời, sự kết hợp giữa vải cấp độ quân sự và đường may cẩn thận của The Overshirt sẽ hoàn thiện vẻ ngoài của bạn. Đây là lớp trên cùng hoàn hảo cho những ngày ấm áp và là lớp giữa khi nhiệt độ giảm xuống. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',310000,4)
insert Products(Title, Preview, Price, CategoryId) values(N'The Overshirt OLIVE',N'Một cổ điển bảo hộ lao động tái sinh. Lấy cảm hứng từ bộ đồng phục công nhân nguyên bản “Bleu de Travail” của Pháp, The Overshirt có đường cắt thẳng, 3 túi trước cổ điển và được thiết kế từ 100% sợi cotton hữu cơ. Dù bạn là MacGyver hay chưa bao giờ sử dụng một công cụ điện nào trong đời, sự kết hợp giữa vải cấp độ quân sự và đường may cẩn thận của The Overshirt sẽ hoàn thiện vẻ ngoài của bạn. Đây là lớp trên cùng hoàn hảo cho những ngày ấm áp và là lớp giữa khi nhiệt độ giảm xuống. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',310000,4)
insert Products(Title, Preview, Price, CategoryId) values(N'The Overshirt BEIGE',N'Một cổ điển bảo hộ lao động tái sinh. Lấy cảm hứng từ bộ đồng phục công nhân nguyên bản “Bleu de Travail” của Pháp, The Overshirt có đường cắt thẳng, 3 túi trước cổ điển và được thiết kế từ 100% sợi cotton hữu cơ. Dù bạn là MacGyver hay chưa bao giờ sử dụng một công cụ điện nào trong đời, sự kết hợp giữa vải cấp độ quân sự và đường may cẩn thận của The Overshirt sẽ hoàn thiện vẻ ngoài của bạn. Đây là lớp trên cùng hoàn hảo cho những ngày ấm áp và là lớp giữa khi nhiệt độ giảm xuống. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',310000,4)
insert Products(Title, Preview, Price, CategoryId) values(N'The Overshirt TAUPE',N'Một cổ điển bảo hộ lao động tái sinh. Lấy cảm hứng từ bộ đồng phục công nhân nguyên bản “Bleu de Travail” của Pháp, The Overshirt có đường cắt thẳng, 3 túi trước cổ điển và được thiết kế từ 100% sợi cotton hữu cơ. Dù bạn là MacGyver hay chưa bao giờ sử dụng một công cụ điện nào trong đời, sự kết hợp giữa vải cấp độ quân sự và đường may cẩn thận của The Overshirt sẽ hoàn thiện vẻ ngoài của bạn. Đây là lớp trên cùng hoàn hảo cho những ngày ấm áp và là lớp giữa khi nhiệt độ giảm xuống. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',310000,4)
insert Products(Title, Preview, Price, CategoryId) values(N'The Overshirt KHAKI GREEN',N'Một cổ điển bảo hộ lao động tái sinh. Lấy cảm hứng từ bộ đồng phục công nhân nguyên bản “Bleu de Travail” của Pháp, The Overshirt có đường cắt thẳng, 3 túi trước cổ điển và được thiết kế từ 100% sợi cotton hữu cơ. Dù bạn là MacGyver hay chưa bao giờ sử dụng một công cụ điện nào trong đời, sự kết hợp giữa vải cấp độ quân sự và đường may cẩn thận của The Overshirt sẽ hoàn thiện vẻ ngoài của bạn. Đây là lớp trên cùng hoàn hảo cho những ngày ấm áp và là lớp giữa khi nhiệt độ giảm xuống. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',310000,4)
insert Products(Title, Preview, Price, CategoryId) values(N'The Overshirt BLACK',N'Một cổ điển bảo hộ lao động tái sinh. Lấy cảm hứng từ bộ đồng phục công nhân nguyên bản “Bleu de Travail” của Pháp, The Overshirt có đường cắt thẳng, 3 túi trước cổ điển và được thiết kế từ 100% sợi cotton hữu cơ. Dù bạn là MacGyver hay chưa bao giờ sử dụng một công cụ điện nào trong đời, sự kết hợp giữa vải cấp độ quân sự và đường may cẩn thận của The Overshirt sẽ hoàn thiện vẻ ngoài của bạn. Đây là lớp trên cùng hoàn hảo cho những ngày ấm áp và là lớp giữa khi nhiệt độ giảm xuống. Hiểu và trân trọng giá trị của trang phục là điều cơ bản trong việc học cách sống tiết kiệm. Chúng ta càng biết nhiều, chúng ta càng đưa ra quyết định tốt hơn, chúng ta càng trân trọng những gì chúng ta có, nó sẽ tồn tại lâu hơn và - kết quả là chúng ta càng cần ít hơn.',310000,4)



select * from ProductMedia

insert ProductMedia(productId, mediaLink) values(1,N't-shirt-1-1.jpg')
insert ProductMedia(productId, mediaLink) values(1,N't-shirt-1-2.jpg')
insert ProductMedia(productId, mediaLink) values(2,N't-shirt-2-1.jpg')
insert ProductMedia(productId, mediaLink) values(2,N't-shirt-2-2.jpg')
insert ProductMedia(productId, mediaLink) values(3,N't-shirt-3-1.jpg')
insert ProductMedia(productId, mediaLink) values(3,N't-shirt-3-2.jpg')
insert ProductMedia(productId, mediaLink) values(4,N't-shirt-4-1.jpg')
insert ProductMedia(productId, mediaLink) values(4,N't-shirt-4-2.jpg')
insert ProductMedia(productId, mediaLink) values(5,N't-shirt-5-1.jpg')
insert ProductMedia(productId, mediaLink) values(5,N't-shirt-5-2.jpg')
insert ProductMedia(productId, mediaLink) values(6,N't-shirt-6-1.jpg')
insert ProductMedia(productId, mediaLink) values(6,N't-shirt-6-2.jpg')
insert ProductMedia(productId, mediaLink) values(7,N't-shirt-7-1.jpg')
insert ProductMedia(productId, mediaLink) values(7,N't-shirt-7-2.jpg')
insert ProductMedia(productId, mediaLink) values(8,N't-shirt-8-1.jpg')
insert ProductMedia(productId, mediaLink) values(8,N't-shirt-8-2.jpg')
insert ProductMedia(productId, mediaLink) values(9,N't-shirt-9-1.jpg')
insert ProductMedia(productId, mediaLink) values(9,N't-shirt-9-2.jpg')
insert ProductMedia(productId, mediaLink) values(10,N't-shirt-10-1.jpg')
insert ProductMedia(productId, mediaLink) values(10,N't-shirt-10-2.jpg')
insert ProductMedia(productId, mediaLink) values(11,N't-shirt-11-1.jpg')
insert ProductMedia(productId, mediaLink) values(11,N't-shirt-11-2.jpg')
insert ProductMedia(productId, mediaLink) values(12,N't-shirt-12-1.jpg')
insert ProductMedia(productId, mediaLink) values(12,N't-shirt-12-2.jpg')
insert ProductMedia(productId, mediaLink) values(13,N't-shirt-13-1.jpg')
insert ProductMedia(productId, mediaLink) values(13,N't-shirt-13-2.jpg')
insert ProductMedia(productId, mediaLink) values(14,N't-shirt-14-1.jpg')
insert ProductMedia(productId, mediaLink) values(14,N't-shirt-14-2.jpg')
insert ProductMedia(productId, mediaLink) values(15,N't-shirt-15-1.jpg')
insert ProductMedia(productId, mediaLink) values(15,N't-shirt-15-2.jpg')
insert ProductMedia(productId, mediaLink) values(16,N't-shirt-16-1.jpg')
insert ProductMedia(productId, mediaLink) values(16,N't-shirt-16-2.jpg')

insert ProductMedia(productId, mediaLink) values(17,N'shirt-1-1.jpg')
insert ProductMedia(productId, mediaLink) values(18,N'shirt-2-1.jpg')
insert ProductMedia(productId, mediaLink) values(19,N'shirt-3-1.jpg')
insert ProductMedia(productId, mediaLink) values(20,N'shirt-4-1.jpg')
insert ProductMedia(productId, mediaLink) values(21,N'shirt-5-1.jpg')
insert ProductMedia(productId, mediaLink) values(22,N'shirt-6-1.jpg')
insert ProductMedia(productId, mediaLink) values(23,N'shirt-7-1.jpg')
insert ProductMedia(productId, mediaLink) values(24,N'shirt-8-1.jpg')
insert ProductMedia(productId, mediaLink) values(25,N'shirt-9-1.jpg')
insert ProductMedia(productId, mediaLink) values(26,N'shirt-10-1.jpg')
insert ProductMedia(productId, mediaLink) values(27,N'shirt-11-1.jpg')
insert ProductMedia(productId, mediaLink) values(28,N'shirt-12-1.jpg')
insert ProductMedia(productId, mediaLink) values(29,N'shirt-13-1.jpg')
insert ProductMedia(productId, mediaLink) values(30,N'shirt-14-1.jpg')
insert ProductMedia(productId, mediaLink) values(31,N'shirt-15-1.jpg')
insert ProductMedia(productId, mediaLink) values(32,N'shirt-16-1.jpg')
insert ProductMedia(productId, mediaLink) values(33,N'shirt-17-1.jpg')
insert ProductMedia(productId, mediaLink) values(34,N'shirt-18-1.jpg')
insert ProductMedia(productId, mediaLink) values(35,N'shirt-19-1.jpg')
insert ProductMedia(productId, mediaLink) values(36,N'shirt-20-1.jpg')
insert ProductMedia(productId, mediaLink) values(37,N'shirt-21-1.jpg')
insert ProductMedia(productId, mediaLink) values(38,N'shirt-22-1.jpg')
insert ProductMedia(productId, mediaLink) values(39,N'shirt-23-1.jpg')
insert ProductMedia(productId, mediaLink) values(40,N'shirt-24-1.jpg')
insert ProductMedia(productId, mediaLink) values(41,N'shirt-25-1.jpg')
insert ProductMedia(productId, mediaLink) values(42,N'shirt-26-1.jpg')
insert ProductMedia(productId, mediaLink) values(43,N'shirt-27-1.jpg')
insert ProductMedia(productId, mediaLink) values(44,N'shirt-28-1.jpg')

insert ProductMedia(productId, mediaLink) values(45,N'sw-shirt-1-1.jpg')
insert ProductMedia(productId, mediaLink) values(46,N'sw-shirt-2-1.jpg')
insert ProductMedia(productId, mediaLink) values(47,N'sw-shirt-3-1.jpg')
insert ProductMedia(productId, mediaLink) values(48,N'sw-shirt-4-1.jpg')
insert ProductMedia(productId, mediaLink) values(49,N'sw-shirt-5-1.jpg')
insert ProductMedia(productId, mediaLink) values(50,N'sw-shirt-6-1.jpg')
insert ProductMedia(productId, mediaLink) values(51,N'sw-shirt-7-1.jpg')
insert ProductMedia(productId, mediaLink) values(52,N'sw-shirt-8-1.jpg')
insert ProductMedia(productId, mediaLink) values(53,N'sw-shirt-9-1.jpg')
insert ProductMedia(productId, mediaLink) values(54,N'sw-shirt-10-1.jpg')
insert ProductMedia(productId, mediaLink) values(55,N'sw-shirt-11-1.jpg')
insert ProductMedia(productId, mediaLink) values(56,N'sw-shirt-12-1.jpg')
insert ProductMedia(productId, mediaLink) values(57,N'sw-shirt-13-1.jpg')
insert ProductMedia(productId, mediaLink) values(58,N'sw-shirt-14-1.jpg')



insert ProductMedia(productId, mediaLink) values(59,N'out-wear-1-1.jpg')
insert ProductMedia(productId, mediaLink) values(60,N'out-wear-2-1.jpg')
insert ProductMedia(productId, mediaLink) values(61,N'out-wear-3-1.jpg')
insert ProductMedia(productId, mediaLink) values(62,N'out-wear-4-1.jpg')
insert ProductMedia(productId, mediaLink) values(63,N'out-wear-5-1.jpg')
insert ProductMedia(productId, mediaLink) values(64,N'out-wear-6-1.jpg')
insert ProductMedia(productId, mediaLink) values(65,N'out-wear-7-1.jpg')
insert ProductMedia(productId, mediaLink) values(66,N'out-wear-8-1.jpg')
insert ProductMedia(productId, mediaLink) values(67,N'out-wear-9-1.jpg')
insert ProductMedia(productId, mediaLink) values(68,N'out-wear-10-1.jpg')
insert ProductMedia(productId, mediaLink) values(69,N'out-wear-11-1.jpg')



select * from Users
select * from USers where username = 'testfw1'

update users set password = N'$2a$10$gX.CHjUX4MDaMi5vaNvJP.E9DBqdkmMwbYrbuhF903o1VHVuvHC3C'
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'qadmin', N'qadmin', N'Q Admin', N'qadmin@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'ALFKI', N'alfki', N'Maria Anders', N'alfki@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'ANATR', N'anatr', N'Ana Trujillo', N'anatr@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'ANTON', N'anton', N'Antonio Moreno', N'anton@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'AROUT', N'arout', N'Thomas Hardy', N'arout@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'BERGS', N'bergs', N'Christina Berglund', N'bergs@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'BLAUS', N'blaus', N'Hanna Moos', N'blaus@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'BLONP', N'blonp', N'Frédérique Citeaux', N'blonp@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'BOLID', N'bolid', N'Martín Sommer', N'bolid@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'BONAP', N'bonap', N'Laurence Lebihan', N'bonap@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'BOTTM', N'bottm', N'Elizabeth Lincoln', N'bottm@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'BSBEV', N'bsbev', N'Victoria Ashworth', N'bsbev@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'CACTU', N'cactu', N'Patricio Simpson', N'cactu@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'CENTC', N'centc', N'Francisco Chang', N'centc@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'CHOPS', N'chops', N'Yang Wang', N'chops@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'COMMI', N'commi', N'Pedro Afonso', N'commi@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'CONSH', N'consh', N'Elizabeth Brown', N'consh@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'customer', N'123', N'Nguyễn Văn Tèo', N'teonv@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'director', N'123', N'Nguyễn Chí Phèo', N'pheonc@fpt.edu.vn', N'-1407968806.jpg')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'DRACD', N'dracd', N'Sven Ottlieb', N'dracd@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'DUMON', N'dumon', N'Janine Labrune', N'dumon@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'EASTC', N'eastc', N'Ann Devon', N'eastc@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'ERNSH', N'ernsh', N'Roland Mendel', N'ernsh@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'FAMIA', N'famia', N'Aria Cruz', N'famia@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'FISSA', N'fissa', N'Diego Roel', N'fissa@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'FOLIG', N'folig', N'Martine Rancé', N'folig@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'FOLKO', N'folko', N'Maria Larsson', N'folko@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'FRANK', N'frank', N'Peter Franken', N'frank@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'FRANR', N'franr', N'Carine Schmitt', N'franr@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'FRANS', N'frans', N'Paolo Accorti', N'frans@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'FURIB', N'furib', N'Lino Rodriguez', N'furib@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'GALED', N'galed', N'Eduardo Saavedra', N'galed@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'GODOS', N'godos', N'José Pedro Freyre', N'godos@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'GOURL', N'gourl', N'André Fonseca', N'gourl@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'GREAL', N'greal', N'Howard Snyder', N'greal@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'GROSR', N'grosr', N'Manuel Pereira', N'grosr@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'HANAR', N'hanar', N'Mario Pontes', N'hanar@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'HILAA', N'hilaa', N'Carlos Hernández', N'hilaa@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'HUNGC', N'hungc', N'Yoshi Latimer', N'hungc@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'HUNGO', N'hungo', N'Patricia McKenna', N'hungo@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'ISLAT', N'islat', N'Helen Bennett', N'islat@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'KOENE', N'koene', N'Philip Cramer', N'koene@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'LACOR', N'lacor', N'Daniel Tonini', N'lacor@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'LAMAI', N'lamai', N'Annette Roulet', N'lamai@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'LAUGB', N'laugb', N'Yoshi Tannamuri', N'laugb@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'LAZYK', N'lazyk', N'John Steel', N'lazyk@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'LEHMS', N'lehms', N'Renate Messner', N'lehms@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'LETSS', N'letss', N'Jaime Yorres', N'letss@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'LILAS', N'lilas', N'Carlos González', N'lilas@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'LINOD', N'linod', N'Felipe Izquierdo', N'linod@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'LONEP', N'lonep', N'Fran Wilson', N'lonep@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'MAGAA', N'magaa', N'Giovanni Rovelli', N'magaa@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'MAISD', N'maisd', N'Catherine Dewey', N'maisd@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'MEREP', N'merep', N'Jean Fresnière', N'merep@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'MORGK', N'morgk', N'Alexander Feuer', N'morgk@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'NORTS', N'norts', N'Simon Crowther', N'norts@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'OCEAN', N'ocean', N'Yvonne Moncada', N'ocean@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'OLDWO', N'oldwo', N'Rene Phillips', N'oldwo@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'OTTIK', N'ottik', N'Henriette Pfalzheim', N'ottik@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'PARIS', N'paris', N'Marie Bertrand', N'paris@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'PERIC', N'peric', N'Guillermo Fernández', N'peric@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'PICCO', N'picco', N'Georg Pipps', N'picco@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'PRINI', N'prini', N'Isabel de Castro', N'prini@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'QUEDE', N'quede', N'Bernardo Batista', N'quede@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'QUEEN', N'queen', N'Lúcia Carvalho', N'queen@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'QUICK', N'quick', N'Horst Kloss', N'quick@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'RANCH', N'ranch', N'Sergio Gutiérrez', N'ranch@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'RATTC', N'rattc', N'Paula Wilson', N'rattc@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'REGGC', N'reggc', N'Maurizio Moroni', N'reggc@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'RICAR', N'ricar', N'Janete Limeira', N'ricar@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'RICSU', N'ricsu', N'Michael Holz', N'ricsu@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'ROMEY', N'romey', N'Alejandra Camino', N'romey@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'SANTG', N'santg', N'Jonas Bergulfsen', N'santg@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'SAVEA', N'savea', N'Jose Pavarotti', N'savea@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'SEVES', N'seves', N'Hari Kumar', N'seves@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'SIMOB', N'simob', N'Jytte Petersen', N'simob@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'SPECD', N'specd', N'Dominique Perrier', N'specd@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'SPLIR', N'splir', N'Art Braunschweiger', N'splir@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'staff', N'123', N'Phạm Thị Nở', N'nopt@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'SUPRD', N'suprd', N'Pascale Cartrain', N'suprd@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'THEBI', N'thebi', N'Liz Nixon', N'thebi@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'THECR', N'thecr', N'Liu Wong', N'thecr@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'TOMSP', N'tomsp', N'Karin Josephs', N'tomsp@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'TORTU', N'tortu', N'Miguel Angel Paolino', N'tortu@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'TRADH', N'tradh', N'Anabela Domingues', N'tradh@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'TRAIH', N'traih', N'Helvetius Nagy', N'traih@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'VAFFE', N'vaffe', N'Palle Ibsen', N'vaffe@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'VICTE', N'victe', N'Mary Saveley', N'victe@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'VINET', N'vinet', N'Paul Henriot', N'vinet@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'WANDK', N'wandk', N'Rita Müller', N'wandk@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'WARTH', N'warth', N'Pirkko Koskitalo', N'warth@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'WELLI', N'welli', N'Paula Parente', N'welli@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'WHITC', N'whitc', N'Karl Jablonski', N'whitc@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'WILMK', N'wilmk', N'Matti Karttunen', N'wilmk@gmail.com', N'user.png')
INSERT Users ([Username], [Password], [Fullname], [Email], [Photo]) VALUES (N'WOLZA', N'wolza', N'Zbyszek Piestrzeniewicz', N'wolza@gmail.com', N'user.png')


select * from Roles

insert Roles (name) values(N'ROLE_USER')
insert Roles (name) values(N'ROLE_EMPLOYEE')
insert Roles (name) values(N'ROLE_ADMIN')

select * from Permission

select * from Permission where username = 'test2'

INSERT Permission ( [Username], [RoleId]) VALUES (N'qadmin', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'qadmin', 2)
INSERT Permission ( [Username], [RoleId]) VALUES (N'qadmin', 3)
INSERT Permission ( [Username], [RoleId]) VALUES (N'ALFKI', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'ANATR', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'ANTON', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'AROUT', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'BERGS', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'BLAUS', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'BLONP', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'BOLID', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'BONAP', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'BOTTM', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'BSBEV', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'CACTU', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'CENTC', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'CHOPS', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'COMMI', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'CONSH', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'DRACD', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'DUMON', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'EASTC', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'ERNSH', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'FAMIA', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'FISSA', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'FOLIG', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'FOLKO', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'FRANK', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'FRANR', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'FRANS', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'FURIB', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'GALED', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'GODOS', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'GOURL', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'GREAL', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'GROSR', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'HANAR', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'HILAA', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'HUNGC', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'HUNGO', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'ISLAT', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'KOENE', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'LACOR', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'LAMAI', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'LAUGB', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'LAZYK', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'LEHMS', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'LETSS', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'LILAS', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'LINOD', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'LONEP', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'MAGAA', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'MAISD', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'MEREP', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'MORGK', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'NORTS', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'OCEAN', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'OLDWO', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'OTTIK', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'PARIS', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'PERIC', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'PICCO', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'PRINI', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'QUEDE', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'QUEEN', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'QUICK', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'RANCH', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'RATTC', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'REGGC', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'RICAR', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'RICSU', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'ROMEY', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'SANTG', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'SAVEA', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'SEVES', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'SIMOB', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'SPECD', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'SPLIR', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'SUPRD', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'customer', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'THEBI', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'THECR', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'TOMSP', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'TORTU', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'TRADH', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'TRAIH', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'VAFFE', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'VICTE', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'VINET', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'WANDK', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'WARTH', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'WELLI', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'WHITC', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'WILMK', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'WOLZA', 1)
INSERT Permission ( [Username], [RoleId]) VALUES (N'director', 3)
INSERT Permission ( [Username], [RoleId]) VALUES (N'staff', 2)
INSERT Permission ( [Username], [RoleId]) VALUES (N'director',2)
INSERT Permission ( [Username], [RoleId]) VALUES (N'staff', 1)

select * from orders
select * from OrderDetail

select * from users where username = '1'